### PR TITLE
docs: update README.md

### PR DESCRIPTION
**Pull request by crashmax-dev**
## Proposed Changes
This PR improved README.md

## Types of changes
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Further comments
Suggest what else can be improved in this PR

### CODE REVIEW

**Review by Cooperbuilt — APPROVED** [review]

**Comment by Cooperbuilt** [comment]
Approved due to the Node update going through in #49

**Comment by Cooperbuilt** [comment]
Hey @crashmax-dev we are ready to merge this for you as soon as you resolve your conflict. Let us know if you need any help getting this over the line and thank you again for your contribution!

**Comment by crashmax-dev** [comment]
@cooperbuilt Maybe there are some other remarks?

**Comment by Cooperbuilt** [comment]
@crashmax-dev looks good to me! Once the pipelines pass we can merge it in

**Pull request merged**
